#21 Logging websocket
logdyn/logdyn-api pull request #22
Opened 2017-06-06 18:15 UTC by jsjlewis96

2017-06-06 18:16 UTC, jsjlewis96 commented
This is only covering websocket registration, use of websockets will have to be reworked after this has been merged

2017-06-07 20:53 UTC, Mattihew requested changes

2017-06-07 20:53 UTC, Mattihew commented on src/main/java/com/logdyn/api/endpoints/LoggingEndpoint.java
> +	private UUID websocketUUID;
websocketUUID does not need to be a field

2017-06-07 20:53 UTC, Mattihew commented on src/main/java/com/logdyn/api/endpoints/LoggingEndpoint.java
> +				set = new ConcurrentHashMap<Session, Void>().keySet();
should instead be `Collections.newSetFromMap(new ConcurrentHashMap<>()`

2017-06-07 20:53 UTC, Mattihew commented on src/main/java/com/logdyn/api/endpoints/LoggingEndpoint.java
> +		final Session websocketSession = LoggingEndpoint.ENDPOINTS.get(websocketId);
change `get` to `remove`

2017-06-07 20:53 UTC, Mattihew commented on src/main/java/com/logdyn/api/endpoints/LoggingEndpoint.java
> +			set = new ConcurrentHashMap<Session, Void>().keySet();
should instead be `Collections.newSetFromMap(new ConcurrentHashMap<>()`

2017-06-07 21:16 UTC, Mattihew approved these changes

2017-06-07 21:16 UTC, merged