added options to log to username
logdyn/logdyn-api pull request #28
Opened 2017-06-10 12:23 UTC by Mattihew

2017-06-12 21:58 UTC, jsjlewis96 commented on src/main/java/com/logdyn/api/endpoints/LogSession.java
> +	public void addExistingSession(final LogSession logSession)
Javadoc please :)

2017-06-12 22:09 UTC, jake-lewis requested changes

2017-06-12 22:09 UTC, jake-lewis commented on src/main/java/com/logdyn/api/endpoints/LogSession.java
> +	public void addExistingSession(final LogSession logSession)
Javadoc please

2017-06-12 22:09 UTC, jsjlewis96 commented on src/main/java/com/logdyn/api/endpoints/LoggingEndpoint.java
> +	public static boolean log(final LogRecord logRecord)
javadoc, also I think general comments throughout this class, as it's the most complex stuff and not the easiest thing to read straight off the bat

2017-06-12 22:09 UTC, jsjlewis96 commented on src/main/java/com/logdyn/api/endpoints/LoggingEndpoint.java
> +	public static boolean clearSession(final String httpSessionId)
javadoc

2017-06-12 22:09 UTC, jsjlewis96 commented on src/main/java/com/logdyn/api/endpoints/LoggingEndpoint.java
> +	public static boolean clearUser(final String username)
javadoc

2017-06-12 22:09 UTC, jsjlewis96 commented on src/main/java/com/logdyn/api/model/LogMessage.java
> +	public LogMessage (final Level level, final String message)
ALL the javadoc that has been removed should probably be replaced

2017-06-14 20:11 UTC, Mattihew commented on src/main/java/com/logdyn/api/model/LogMessage.java
> +	public LogMessage (final Level level, final String message)
this whole class will hopfully be removed soon. i'll comment it if it turns out its staying

2017-06-14 21:38 UTC, jake-lewis approved these changes

2017-06-14 21:38 UTC, merged